package net.dean.jraw.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import net.dean.jraw.databind.RedditModel
import java.io.Serializable

@RedditModel
@JsonClass(generateAdapter = true)
data class Trophy(
    /** A succinct description of how/when/why the user got this award  */
    @Json(name = "description") val description: String?,

    /** Trophy name (e.g. "Five-Year Club")  */
    @Json(name = "name") override val fullName: String,

    /**
     * An optional URL that highlights where/how the user gained the trophy. If this URL is relative, it is relative to
     * `reddit.com`
     */
    @Json(name = "url") val url: String?,

    /** A unique ID generated by reddit, if any  */
    @Json(name = "id") override val id: String,

    /** The 40x40 icon for this Trophy  */
    @Json(name = "icon_40") val icon40: String?,

    /** The 70x70 icon for this Trophy  */
    @Json(name = "icon_70") val icon70: String?,
) : Identifiable, Serializable {

    override val uniqueId: String
        get() = fullName
}
